# Generated by Django 5.2.6 on 2025-10-02 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(verbose_name='ID пользователя Telegram')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('paid', 'Оплачен'), ('accepted', 'Принят'), ('rejected', 'Отклонен'), ('completed', 'Завершен')], default='created', max_length=20, verbose_name='Статус заказа')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая сумма заказа')),
                ('address', models.CharField(blank=True, max_length=512, verbose_name='Адрес доставки')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='Дополнительная информация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('description', models.TextField(blank=True, verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена товара')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Ссылка на изображение')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Мета-данные товара')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена позиции')),
                ('options', models.JSONField(blank=True, default=dict, verbose_name='Выбранные опции')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mainapp.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'позицию заказа',
                'verbose_name_plural': 'Позиции заказов',
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название опции')),
                ('values', models.JSONField(default=list, verbose_name='Значения опции')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='mainapp.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'опцию товара',
                'verbose_name_plural': 'Опции товаров',
            },
        ),
    ]
